# Copyright (c) 2022-2024 Contributors to the Eclipse Foundation
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: documentation-package
description: This action adds files from various tools to the release documentation.

inputs:
  name:
    description: "Arbitrary name for the artifact"
    required: true
  type:
    description: "Type of the artifact"
    required: true
  schema:
    description: "Schema of the files"
    required: true
  sourcePath:
    description: "Folder where the action retrieves the raw result files"
    required: true
  packagePath:
    description: "Target path where the results are copied to"
    required: true
runs:
  using: "composite"
  steps:
    - name: Create package path folder
      shell: bash
      run: |
        echo "Create package path folder"
        mkdir -p ${{ inputs.packagePath }}/${{ inputs.name }}
    - name: Copy files from source to destination folder
      shell: bash
      run: |
        echo "Copy files from source to destination folder"
        if [[ -d ${{ inputs.sourcePath }} ]]; then
          cp -R ${{ inputs.sourcePath }}/* ${{ inputs.packagePath }}/${{ inputs.name }}
        else
          cp ${{ inputs.sourcePath }} ${{ inputs.packagePath }}/${{ inputs.name }}
        fi
        ls -la ${{ inputs.packagePath }}/${{ inputs.name }}
    - name: Create test artifact
      shell: bash
      run: |
        echo "Create test artifact file"
        cat > ${{ inputs.packagePath }}/${{ inputs.name }}/TestArtifact.json <<EOL
        {
            "Name": "${{ inputs.name }}",
            "CommitHash": "$GITHUB_SHA",
            "Type": "${{ inputs.type }}",
            "Schema": "${{ inputs.schema }}"
        }
        EOL
